name: Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t your-app .
          docker run --name app your-app

      - name: Copy build artifacts from Docker container
        run: docker cp app:/app/build .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # replace with your preferred AWS region

      - name: Sync build artifacts to S3
        run: aws s3 sync build/ s3://your-s3-bucket-name
